#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWQ1NjdkMTVmYzc1MjZiYmIxOWI5MTVjOTQzODRhODM5MzA2MjYxMDM1Yjk5ODBkOWFlMjFmNTA5OTZkMGYwMmRlMWE1YmNiNTdmMGVlNzNhOTJiNGJmYzJlOGFiMDlhYzU4Nw==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
