version: '2'
services:
  partener-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/partener/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=partener
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
